//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 01:25:35 PM CEST 
//


package es.bankia.n28.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.carm.ea.schemas.funcionales.pagobanco.cargocuentatelematica package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.carm.ea.schemas.funcionales.pagobanco.cargocuentatelematica
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlBody }
     * 
     */
    public XmlBody createLIQUIDACIONAUTOLIQUIDACION() {
        return new XmlBody();
    }

    /**
     * Create an instance of {@link XmlBody.REPLY }
     * 
     */
    public XmlBody.REPLY createLIQUIDACIONAUTOLIQUIDACIONREPLY() {
        return new XmlBody.REPLY();
    }

    /**
     * Create an instance of {@link XmlBody.REPLY.RESPUESTALOTE }
     * 
     */
    public XmlBody.REPLY.RESPUESTALOTE createLIQUIDACIONAUTOLIQUIDACIONREPLYRESPUESTALOTE() {
        return new XmlBody.REPLY.RESPUESTALOTE();
    }

    /**
     * Create an instance of {@link XmlBody.REQUEST }
     * 
     */
    public XmlBody.REQUEST createLIQUIDACIONAUTOLIQUIDACIONREQUEST() {
        return new XmlBody.REQUEST();
    }

    /**
     * Create an instance of {@link XmlBody.REQUEST.LOTE }
     * 
     */
    public XmlBody.REQUEST.LOTE createLIQUIDACIONAUTOLIQUIDACIONREQUESTLOTE() {
        return new XmlBody.REQUEST.LOTE();
    }

    /**
     * Create an instance of {@link XmlBody.REQUEST.LOTE.CARGO }
     * 
     */
    public XmlBody.REQUEST.LOTE.CARGO createLIQUIDACIONAUTOLIQUIDACIONREQUESTLOTECARGO() {
        return new XmlBody.REQUEST.LOTE.CARGO();
    }

    /**
     * Create an instance of {@link XmlBody.VALIDACION }
     * 
     */
    public XmlBody.VALIDACION createLIQUIDACIONAUTOLIQUIDACIONVALIDACION() {
        return new XmlBody.VALIDACION();
    }

    /**
     * Create an instance of {@link XmlHeader }
     * 
     */
    public XmlHeader createCABECERAMENSAJETYPE() {
        return new XmlHeader();
    }

    /**
     * Create an instance of {@link XmlHolder }
     * 
     */
    public XmlHolder createINTERVINIENTE() {
        return new XmlHolder();
    }

    /**
     * Create an instance of {@link XmlBody.REPLY.RESPUESTALOTE.DETALLECARGO }
     * 
     */
    public XmlBody.REPLY.RESPUESTALOTE.DETALLECARGO createLIQUIDACIONAUTOLIQUIDACIONREPLYRESPUESTALOTEDETALLECARGO() {
        return new XmlBody.REPLY.RESPUESTALOTE.DETALLECARGO();
    }

    /**
     * Create an instance of {@link XmlBody.REQUEST.URLCOMUNICACION }
     * 
     */
    public XmlBody.REQUEST.URLCOMUNICACION createLIQUIDACIONAUTOLIQUIDACIONREQUESTURLCOMUNICACION() {
        return new XmlBody.REQUEST.URLCOMUNICACION();
    }

    /**
     * Create an instance of {@link XmlBody.REQUEST.LOTE.DETALLEINGRESO }
     * 
     */
    public XmlBody.REQUEST.LOTE.DETALLEINGRESO createLIQUIDACIONAUTOLIQUIDACIONREQUESTLOTEDETALLEINGRESO() {
        return new XmlBody.REQUEST.LOTE.DETALLEINGRESO();
    }

    /**
     * Create an instance of {@link XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO }
     * 
     */
    public XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO createLIQUIDACIONAUTOLIQUIDACIONREQUESTLOTECARGOCUENTACARGO() {
        return new XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO();
    }

}
