//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 01:25:35 PM CEST 
//


package es.bankia.n28.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CABECERA_MENSAJE_TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CABECERA_MENSAJE_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID_COMUNICACION" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ID_COMUNICACIONType"/>
 *         &lt;element name="APLICACION" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}APLICACIONType"/>
 *         &lt;element name="FECHA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}FECHAType"/>
 *         &lt;element name="HORA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}HORAType"/>
 *         &lt;element name="EMISOR" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}EMISORType"/>
 *         &lt;element name="RECEPTOR" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}RECEPTORType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CABECERA_MENSAJE_TYPE", propOrder = {
    "idcomunicacion",
    "aplicacion",
    "fecha",
    "hora",
    "emisor",
    "receptor"
})
public class XmlHeader {

    @XmlElement(name = "ID_COMUNICACION", required = true)
    protected String idcomunicacion;
    @XmlElement(name = "APLICACION", required = true)
    protected String aplicacion;
    @XmlElement(name = "FECHA", required = true)
    protected String fecha;
    @XmlElement(name = "HORA", required = true)
    protected String hora;
    @XmlElement(name = "EMISOR", required = true)
    protected String emisor;
    @XmlElement(name = "RECEPTOR", required = true)
    protected String receptor;

    /**
     * Gets the value of the idcomunicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCOMUNICACION() {
        return idcomunicacion;
    }

    /**
     * Sets the value of the idcomunicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCOMUNICACION(String value) {
        this.idcomunicacion = value;
    }

    /**
     * Gets the value of the aplicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPLICACION() {
        return aplicacion;
    }

    /**
     * Sets the value of the aplicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPLICACION(String value) {
        this.aplicacion = value;
    }

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHA() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHA(String value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the hora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHORA() {
        return hora;
    }

    /**
     * Sets the value of the hora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHORA(String value) {
        this.hora = value;
    }

    /**
     * Gets the value of the emisor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMISOR() {
        return emisor;
    }

    /**
     * Sets the value of the emisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMISOR(String value) {
        this.emisor = value;
    }

    /**
     * Gets the value of the receptor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEPTOR() {
        return receptor;
    }

    /**
     * Sets the value of the receptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEPTOR(String value) {
        this.receptor = value;
    }

}
