//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 01:25:35 PM CEST 
//


package es.bankia.n28.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Cualquier persona o tercero interviniente (sujeto pasivo, representante, titular de cuenta)
 * 
 * <p>Java class for INTERVINIENTE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INTERVINIENTE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NIF_CIF" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NIF_CIFType"/>
 *         &lt;element name="NOMBRE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NOMBREType">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="APELLIDO_1" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}APELLIDOType" minOccurs="0"/>
 *         &lt;element name="APELLIDO_2" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}APELLIDOType" minOccurs="0"/>
 *         &lt;element name="RAZON_SOCIAL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INTERVINIENTE", propOrder = {
    "nifcif",
    "nombre",
    "apellido1",
    "apellido2",
    "razonsocial"
})
public class XmlHolder {

    @XmlElement(name = "NIF_CIF", required = true)
    protected String nifcif;
    @XmlElement(name = "NOMBRE")
    protected String nombre;
    @XmlElement(name = "APELLIDO_1")
    protected String apellido1;
    @XmlElement(name = "APELLIDO_2")
    protected String apellido2;
    @XmlElement(name = "RAZON_SOCIAL")
    protected String razonsocial;

    /**
     * Gets the value of the nifcif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIFCIF() {
        return nifcif;
    }

    /**
     * Sets the value of the nifcif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIFCIF(String value) {
        this.nifcif = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMBRE() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMBRE(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the apellido1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPELLIDO1() {
        return apellido1;
    }

    /**
     * Sets the value of the apellido1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPELLIDO1(String value) {
        this.apellido1 = value;
    }

    /**
     * Gets the value of the apellido2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPELLIDO2() {
        return apellido2;
    }

    /**
     * Sets the value of the apellido2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPELLIDO2(String value) {
        this.apellido2 = value;
    }

    /**
     * Gets the value of the razonsocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRAZONSOCIAL() {
        return razonsocial;
    }

    /**
     * Sets the value of the razonsocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRAZONSOCIAL(String value) {
        this.razonsocial = value;
    }

}
