//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.25 at 01:25:35 PM CEST 
//


package es.bankia.n28.cifrado.beans;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="REQUEST">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CABECERA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}CABECERA_MENSAJE_TYPE"/>
 *                   &lt;element name="URL_COMUNICACION">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="URL_VUELTA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="URL_NOTIFICACION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="LOTE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ID_LOTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IMP_TOTAL_LOTE" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
 *                             &lt;element name="NUM_DETALLE" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DETALLEType"/>
 *                             &lt;element name="TIPO_SERVICIO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}TIPO_SERVICIOType"/>
 *                             &lt;element name="CARGO">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TITULAR_CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NIF_CIFType"/>
 *                                       &lt;element name="CUENTA_CARGO">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ENTIDAD" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType" minOccurs="0"/>
 *                                                 &lt;element name="SUCURSAL" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}SUCURSALType" minOccurs="0"/>
 *                                                 &lt;element name="D_C" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DCType" minOccurs="0"/>
 *                                                 &lt;element name="CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NUM_CUENTAType" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="DETALLE_INGRESO" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
 *                                       &lt;element name="IMPORTE_INGRESO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
 *                                       &lt;element name="SUJETO_PASIVO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}INTERVINIENTE"/>
 *                                       &lt;element name="OLDH" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}OLDHType"/>
 *                                       &lt;element name="HECHO_IMP">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}HECHO_IMPONIBLEType">
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="MACODE">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
 *                                             &lt;maxLength value="16"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="REPLY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CABECERA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}CABECERA_MENSAJE_TYPE"/>
 *                   &lt;element name="RESPUESTA_LOTE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ID_LOTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NUM_DETALLE" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                             &lt;element name="NUM_CARGOS" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                             &lt;element name="DETALLE_CARGO" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RESULTADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
 *                                       &lt;element name="ENTIDAD_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType"/>
 *                                       &lt;element name="FECHA_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}FECHAType"/>
 *                                       &lt;element name="IMPORTE_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
 *                                       &lt;element name="MAC_CCT">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
 *                                             &lt;maxLength value="16"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="VALIDACION_CCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VALIDACION" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CODIGO_ERROR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TEXTO_ERROR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "reply",
    "validacion"
})
@XmlRootElement(name = "LIQUIDACION_AUTOLIQUIDACION")
public class XmlBody {

    @XmlElement(name = "REQUEST")
    protected XmlBody.REQUEST request;
    @XmlElement(name = "REPLY")
    protected XmlBody.REPLY reply;
    @XmlElement(name = "VALIDACION")
    protected XmlBody.VALIDACION validacion;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link XmlBody.REQUEST }
     *     
     */
    public XmlBody.REQUEST getREQUEST() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlBody.REQUEST }
     *     
     */
    public void setREQUEST(XmlBody.REQUEST value) {
        this.request = value;
    }

    /**
     * Gets the value of the reply property.
     * 
     * @return
     *     possible object is
     *     {@link XmlBody.REPLY }
     *     
     */
    public XmlBody.REPLY getREPLY() {
        return reply;
    }

    /**
     * Sets the value of the reply property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlBody.REPLY }
     *     
     */
    public void setREPLY(XmlBody.REPLY value) {
        this.reply = value;
    }

    /**
     * Gets the value of the validacion property.
     * 
     * @return
     *     possible object is
     *     {@link XmlBody.VALIDACION }
     *     
     */
    public XmlBody.VALIDACION getVALIDACION() {
        return validacion;
    }

    /**
     * Sets the value of the validacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlBody.VALIDACION }
     *     
     */
    public void setVALIDACION(XmlBody.VALIDACION value) {
        this.validacion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CABECERA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}CABECERA_MENSAJE_TYPE"/>
     *         &lt;element name="RESPUESTA_LOTE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ID_LOTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NUM_DETALLE" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                   &lt;element name="NUM_CARGOS" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                   &lt;element name="DETALLE_CARGO" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RESULTADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
     *                             &lt;element name="ENTIDAD_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType"/>
     *                             &lt;element name="FECHA_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}FECHAType"/>
     *                             &lt;element name="IMPORTE_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
     *                             &lt;element name="MAC_CCT">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
     *                                   &lt;maxLength value="16"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="VALIDACION_CCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cabecera",
        "respuestalote"
    })
    public static class REPLY {

        @XmlElement(name = "CABECERA", required = true)
        protected XmlHeader cabecera;
        @XmlElement(name = "RESPUESTA_LOTE", required = true)
        protected XmlBody.REPLY.RESPUESTALOTE respuestalote;

        /**
         * Gets the value of the cabecera property.
         * 
         * @return
         *     possible object is
         *     {@link XmlHeader }
         *     
         */
        public XmlHeader getCABECERA() {
            return cabecera;
        }

        /**
         * Sets the value of the cabecera property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlHeader }
         *     
         */
        public void setCABECERA(XmlHeader value) {
            this.cabecera = value;
        }

        /**
         * Gets the value of the respuestalote property.
         * 
         * @return
         *     possible object is
         *     {@link XmlBody.REPLY.RESPUESTALOTE }
         *     
         */
        public XmlBody.REPLY.RESPUESTALOTE getRESPUESTALOTE() {
            return respuestalote;
        }

        /**
         * Sets the value of the respuestalote property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlBody.REPLY.RESPUESTALOTE }
         *     
         */
        public void setRESPUESTALOTE(XmlBody.REPLY.RESPUESTALOTE value) {
            this.respuestalote = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ID_LOTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NUM_DETALLE" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *         &lt;element name="NUM_CARGOS" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *         &lt;element name="DETALLE_CARGO" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RESULTADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
         *                   &lt;element name="ENTIDAD_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType"/>
         *                   &lt;element name="FECHA_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}FECHAType"/>
         *                   &lt;element name="IMPORTE_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
         *                   &lt;element name="MAC_CCT">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
         *                         &lt;maxLength value="16"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="VALIDACION_CCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idlote",
            "numdetalle",
            "numcargos",
            "detallecargo"
        })
        public static class RESPUESTALOTE {

            @XmlElement(name = "ID_LOTE", required = true)
            protected String idlote;
            @XmlElement(name = "NUM_DETALLE", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger numdetalle;
            @XmlElement(name = "NUM_CARGOS", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger numcargos;
            @XmlElement(name = "DETALLE_CARGO", required = true)
            protected List<XmlBody.REPLY.RESPUESTALOTE.DETALLECARGO> detallecargo;

            /**
             * Gets the value of the idlote property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIDLOTE() {
                return idlote;
            }

            /**
             * Sets the value of the idlote property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIDLOTE(String value) {
                this.idlote = value;
            }

            /**
             * Gets the value of the numdetalle property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNUMDETALLE() {
                return numdetalle;
            }

            /**
             * Sets the value of the numdetalle property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNUMDETALLE(BigInteger value) {
                this.numdetalle = value;
            }

            /**
             * Gets the value of the numcargos property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNUMCARGOS() {
                return numcargos;
            }

            /**
             * Sets the value of the numcargos property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNUMCARGOS(BigInteger value) {
                this.numcargos = value;
            }

            /**
             * Gets the value of the detallecargo property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the detallecargo property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDETALLECARGO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XmlBody.REPLY.RESPUESTALOTE.DETALLECARGO }
             * 
             * 
             */
            public List<XmlBody.REPLY.RESPUESTALOTE.DETALLECARGO> getDETALLECARGO() {
                if (detallecargo == null) {
                    detallecargo = new ArrayList<XmlBody.REPLY.RESPUESTALOTE.DETALLECARGO>();
                }
                return this.detallecargo;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RESULTADO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
             *         &lt;element name="ENTIDAD_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType"/>
             *         &lt;element name="FECHA_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}FECHAType"/>
             *         &lt;element name="IMPORTE_ING" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
             *         &lt;element name="MAC_CCT">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
             *               &lt;maxLength value="16"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="VALIDACION_CCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "resultado",
                "idunico",
                "entidading",
                "fechaing",
                "importeing",
                "maccct",
                "validacioncct"
            })
            public static class DETALLECARGO {

                @XmlElement(name = "RESULTADO", required = true)
                protected String resultado;
                @XmlElement(name = "ID_UNICO", required = true)
                protected String idunico;
                @XmlElement(name = "ENTIDAD_ING", required = true)
                protected String entidading;
                @XmlElement(name = "FECHA_ING", required = true)
                protected String fechaing;
                @XmlElement(name = "IMPORTE_ING", required = true)
                protected String importeing;
                @XmlElement(name = "MAC_CCT", required = true)
                protected String maccct;
                @XmlElement(name = "VALIDACION_CCT")
                protected String validacioncct;

                /**
                 * Gets the value of the resultado property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRESULTADO() {
                    return resultado;
                }

                /**
                 * Sets the value of the resultado property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRESULTADO(String value) {
                    this.resultado = value;
                }

                /**
                 * Gets the value of the idunico property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIDUNICO() {
                    return idunico;
                }

                /**
                 * Sets the value of the idunico property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIDUNICO(String value) {
                    this.idunico = value;
                }

                /**
                 * Gets the value of the entidading property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getENTIDADING() {
                    return entidading;
                }

                /**
                 * Sets the value of the entidading property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setENTIDADING(String value) {
                    this.entidading = value;
                }

                /**
                 * Gets the value of the fechaing property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFECHAING() {
                    return fechaing;
                }

                /**
                 * Sets the value of the fechaing property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFECHAING(String value) {
                    this.fechaing = value;
                }

                /**
                 * Gets the value of the importeing property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIMPORTEING() {
                    return importeing;
                }

                /**
                 * Sets the value of the importeing property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIMPORTEING(String value) {
                    this.importeing = value;
                }

                /**
                 * Gets the value of the maccct property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMACCCT() {
                    return maccct;
                }

                /**
                 * Sets the value of the maccct property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMACCCT(String value) {
                    this.maccct = value;
                }

                /**
                 * Gets the value of the validacioncct property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVALIDACIONCCT() {
                    return validacioncct;
                }

                /**
                 * Sets the value of the validacioncct property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVALIDACIONCCT(String value) {
                    this.validacioncct = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CABECERA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}CABECERA_MENSAJE_TYPE"/>
     *         &lt;element name="URL_COMUNICACION">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="URL_VUELTA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="URL_NOTIFICACION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="LOTE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ID_LOTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IMP_TOTAL_LOTE" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
     *                   &lt;element name="NUM_DETALLE" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DETALLEType"/>
     *                   &lt;element name="TIPO_SERVICIO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}TIPO_SERVICIOType"/>
     *                   &lt;element name="CARGO">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TITULAR_CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NIF_CIFType"/>
     *                             &lt;element name="CUENTA_CARGO">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ENTIDAD" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType" minOccurs="0"/>
     *                                       &lt;element name="SUCURSAL" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}SUCURSALType" minOccurs="0"/>
     *                                       &lt;element name="D_C" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DCType" minOccurs="0"/>
     *                                       &lt;element name="CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NUM_CUENTAType" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DETALLE_INGRESO" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
     *                             &lt;element name="IMPORTE_INGRESO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
     *                             &lt;element name="SUJETO_PASIVO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}INTERVINIENTE"/>
     *                             &lt;element name="OLDH" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}OLDHType"/>
     *                             &lt;element name="HECHO_IMP">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}HECHO_IMPONIBLEType">
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="MACODE">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
     *                                   &lt;maxLength value="16"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cabecera",
        "urlcomunicacion",
        "lote"
    })
    public static class REQUEST {

        @XmlElement(name = "CABECERA", required = true)
        protected XmlHeader cabecera;
        @XmlElement(name = "URL_COMUNICACION", required = true)
        protected XmlBody.REQUEST.URLCOMUNICACION urlcomunicacion;
        @XmlElement(name = "LOTE", required = true)
        protected XmlBody.REQUEST.LOTE lote;

        /**
         * Gets the value of the cabecera property.
         * 
         * @return
         *     possible object is
         *     {@link XmlHeader }
         *     
         */
        public XmlHeader getCABECERA() {
            return cabecera;
        }

        /**
         * Sets the value of the cabecera property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlHeader }
         *     
         */
        public void setCABECERA(XmlHeader value) {
            this.cabecera = value;
        }

        /**
         * Gets the value of the urlcomunicacion property.
         * 
         * @return
         *     possible object is
         *     {@link XmlBody.REQUEST.URLCOMUNICACION }
         *     
         */
        public XmlBody.REQUEST.URLCOMUNICACION getURLCOMUNICACION() {
            return urlcomunicacion;
        }

        /**
         * Sets the value of the urlcomunicacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlBody.REQUEST.URLCOMUNICACION }
         *     
         */
        public void setURLCOMUNICACION(XmlBody.REQUEST.URLCOMUNICACION value) {
            this.urlcomunicacion = value;
        }

        /**
         * Gets the value of the lote property.
         * 
         * @return
         *     possible object is
         *     {@link XmlBody.REQUEST.LOTE }
         *     
         */
        public XmlBody.REQUEST.LOTE getLOTE() {
            return lote;
        }

        /**
         * Sets the value of the lote property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlBody.REQUEST.LOTE }
         *     
         */
        public void setLOTE(XmlBody.REQUEST.LOTE value) {
            this.lote = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ID_LOTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IMP_TOTAL_LOTE" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
         *         &lt;element name="NUM_DETALLE" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DETALLEType"/>
         *         &lt;element name="TIPO_SERVICIO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}TIPO_SERVICIOType"/>
         *         &lt;element name="CARGO">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TITULAR_CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NIF_CIFType"/>
         *                   &lt;element name="CUENTA_CARGO">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ENTIDAD" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType" minOccurs="0"/>
         *                             &lt;element name="SUCURSAL" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}SUCURSALType" minOccurs="0"/>
         *                             &lt;element name="D_C" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DCType" minOccurs="0"/>
         *                             &lt;element name="CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NUM_CUENTAType" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DETALLE_INGRESO" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
         *                   &lt;element name="IMPORTE_INGRESO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
         *                   &lt;element name="SUJETO_PASIVO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}INTERVINIENTE"/>
         *                   &lt;element name="OLDH" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}OLDHType"/>
         *                   &lt;element name="HECHO_IMP">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}HECHO_IMPONIBLEType">
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="MACODE">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
         *                         &lt;maxLength value="16"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idlote",
            "imptotallote",
            "numdetalle",
            "tiposervicio",
            "cargo",
            "detalleingreso"
        })
        public static class LOTE {

            @XmlElement(name = "ID_LOTE", required = true)
            protected String idlote;
            @XmlElement(name = "IMP_TOTAL_LOTE", required = true)
            protected String imptotallote;
            @XmlElement(name = "NUM_DETALLE", required = true)
            protected String numdetalle;
            @XmlElement(name = "TIPO_SERVICIO", required = true)
            protected String tiposervicio;
            @XmlElement(name = "CARGO", required = true)
            protected XmlBody.REQUEST.LOTE.CARGO cargo;
            @XmlElement(name = "DETALLE_INGRESO", required = true)
            protected List<XmlBody.REQUEST.LOTE.DETALLEINGRESO> detalleingreso;

            /**
             * Gets the value of the idlote property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIDLOTE() {
                return idlote;
            }

            /**
             * Sets the value of the idlote property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIDLOTE(String value) {
                this.idlote = value;
            }

            /**
             * Gets the value of the imptotallote property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIMPTOTALLOTE() {
                return imptotallote;
            }

            /**
             * Sets the value of the imptotallote property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIMPTOTALLOTE(String value) {
                this.imptotallote = value;
            }

            /**
             * Gets the value of the numdetalle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNUMDETALLE() {
                return numdetalle;
            }

            /**
             * Sets the value of the numdetalle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNUMDETALLE(String value) {
                this.numdetalle = value;
            }

            /**
             * Gets the value of the tiposervicio property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTIPOSERVICIO() {
                return tiposervicio;
            }

            /**
             * Sets the value of the tiposervicio property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTIPOSERVICIO(String value) {
                this.tiposervicio = value;
            }

            /**
             * Gets the value of the cargo property.
             * 
             * @return
             *     possible object is
             *     {@link XmlBody.REQUEST.LOTE.CARGO }
             *     
             */
            public XmlBody.REQUEST.LOTE.CARGO getCARGO() {
                return cargo;
            }

            /**
             * Sets the value of the cargo property.
             * 
             * @param value
             *     allowed object is
             *     {@link XmlBody.REQUEST.LOTE.CARGO }
             *     
             */
            public void setCARGO(XmlBody.REQUEST.LOTE.CARGO value) {
                this.cargo = value;
            }

            /**
             * Gets the value of the detalleingreso property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the detalleingreso property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDETALLEINGRESO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XmlBody.REQUEST.LOTE.DETALLEINGRESO }
             * 
             * 
             */
            public List<XmlBody.REQUEST.LOTE.DETALLEINGRESO> getDETALLEINGRESO() {
                if (detalleingreso == null) {
                    detalleingreso = new ArrayList<XmlBody.REQUEST.LOTE.DETALLEINGRESO>();
                }
                return this.detalleingreso;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TITULAR_CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NIF_CIFType"/>
             *         &lt;element name="CUENTA_CARGO">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ENTIDAD" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType" minOccurs="0"/>
             *                   &lt;element name="SUCURSAL" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}SUCURSALType" minOccurs="0"/>
             *                   &lt;element name="D_C" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DCType" minOccurs="0"/>
             *                   &lt;element name="CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NUM_CUENTAType" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "titularcuenta",
                "cuentacargo"
            })
            public static class CARGO {

                @XmlElement(name = "TITULAR_CUENTA", required = true)
                protected String titularcuenta;
                @XmlElement(name = "CUENTA_CARGO", required = true)
                protected XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO cuentacargo;

                /**
                 * Gets the value of the titularcuenta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTITULARCUENTA() {
                    return titularcuenta;
                }

                /**
                 * Sets the value of the titularcuenta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTITULARCUENTA(String value) {
                    this.titularcuenta = value;
                }

                /**
                 * Gets the value of the cuentacargo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO }
                 *     
                 */
                public XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO getCUENTACARGO() {
                    return cuentacargo;
                }

                /**
                 * Sets the value of the cuentacargo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO }
                 *     
                 */
                public void setCUENTACARGO(XmlBody.REQUEST.LOTE.CARGO.CUENTACARGO value) {
                    this.cuentacargo = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ENTIDAD" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}ENTIDADType" minOccurs="0"/>
                 *         &lt;element name="SUCURSAL" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}SUCURSALType" minOccurs="0"/>
                 *         &lt;element name="D_C" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}DCType" minOccurs="0"/>
                 *         &lt;element name="CUENTA" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}NUM_CUENTAType" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "entidad",
                    "sucursal",
                    "dc",
                    "cuenta"
                })
                public static class CUENTACARGO {

                    @XmlElement(name = "ENTIDAD")
                    protected String entidad;
                    @XmlElement(name = "SUCURSAL")
                    protected String sucursal;
                    @XmlElement(name = "D_C")
                    protected String dc;
                    @XmlElement(name = "CUENTA")
                    protected String cuenta;

                    /**
                     * Gets the value of the entidad property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getENTIDAD() {
                        return entidad;
                    }

                    /**
                     * Sets the value of the entidad property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setENTIDAD(String value) {
                        this.entidad = value;
                    }

                    /**
                     * Gets the value of the sucursal property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSUCURSAL() {
                        return sucursal;
                    }

                    /**
                     * Sets the value of the sucursal property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSUCURSAL(String value) {
                        this.sucursal = value;
                    }

                    /**
                     * Gets the value of the dc property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDC() {
                        return dc;
                    }

                    /**
                     * Sets the value of the dc property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDC(String value) {
                        this.dc = value;
                    }

                    /**
                     * Gets the value of the cuenta property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCUENTA() {
                        return cuenta;
                    }

                    /**
                     * Sets the value of the cuenta property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCUENTA(String value) {
                        this.cuenta = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ID_UNICO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}N28Type"/>
             *         &lt;element name="IMPORTE_INGRESO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}IMPORTEType"/>
             *         &lt;element name="SUJETO_PASIVO" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}INTERVINIENTE"/>
             *         &lt;element name="OLDH" type="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}OLDHType"/>
             *         &lt;element name="HECHO_IMP">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}HECHO_IMPONIBLEType">
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="MACODE">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://ea.carm.es/schemas/funcionales/pagoBanco/CargoCuentaTelematica.xsd}MACODEType">
             *               &lt;maxLength value="16"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idunico",
                "importeingreso",
                "sujetopasivo",
                "oldh",
                "hechoimp",
                "macode"
            })
            public static class DETALLEINGRESO {

                @XmlElement(name = "ID_UNICO", required = true)
                protected String idunico;
                @XmlElement(name = "IMPORTE_INGRESO", required = true)
                protected String importeingreso;
                @XmlElement(name = "SUJETO_PASIVO", required = true)
                protected XmlHolder sujetopasivo;
                @XmlElement(name = "OLDH", required = true)
                protected String oldh;
                @XmlElement(name = "HECHO_IMP", required = true)
                protected String hechoimp;
                @XmlElement(name = "MACODE", required = true)
                protected String macode;

                /**
                 * Gets the value of the idunico property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIDUNICO() {
                    return idunico;
                }

                /**
                 * Sets the value of the idunico property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIDUNICO(String value) {
                    this.idunico = value;
                }

                /**
                 * Gets the value of the importeingreso property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIMPORTEINGRESO() {
                    return importeingreso;
                }

                /**
                 * Sets the value of the importeingreso property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIMPORTEINGRESO(String value) {
                    this.importeingreso = value;
                }

                /**
                 * Gets the value of the sujetopasivo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XmlHolder }
                 *     
                 */
                public XmlHolder getSUJETOPASIVO() {
                    return sujetopasivo;
                }

                /**
                 * Sets the value of the sujetopasivo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XmlHolder }
                 *     
                 */
                public void setSUJETOPASIVO(XmlHolder value) {
                    this.sujetopasivo = value;
                }

                /**
                 * Gets the value of the oldh property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOLDH() {
                    return oldh;
                }

                /**
                 * Sets the value of the oldh property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOLDH(String value) {
                    this.oldh = value;
                }

                /**
                 * Gets the value of the hechoimp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHECHOIMP() {
                    return hechoimp;
                }

                /**
                 * Sets the value of the hechoimp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHECHOIMP(String value) {
                    this.hechoimp = value;
                }

                /**
                 * Gets the value of the macode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMACODE() {
                    return macode;
                }

                /**
                 * Sets the value of the macode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMACODE(String value) {
                    this.macode = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="URL_VUELTA" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="URL_NOTIFICACION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "urlvuelta",
            "urlnotificacion"
        })
        public static class URLCOMUNICACION {

            @XmlElement(name = "URL_VUELTA", required = true)
            protected String urlvuelta;
            @XmlElement(name = "URL_NOTIFICACION", required = true)
            protected String urlnotificacion;

            /**
             * Gets the value of the urlvuelta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getURLVUELTA() {
                return urlvuelta;
            }

            /**
             * Sets the value of the urlvuelta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setURLVUELTA(String value) {
                this.urlvuelta = value;
            }

            /**
             * Gets the value of the urlnotificacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getURLNOTIFICACION() {
                return urlnotificacion;
            }

            /**
             * Sets the value of the urlnotificacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setURLNOTIFICACION(String value) {
                this.urlnotificacion = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CODIGO_ERROR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TEXTO_ERROR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codigoerror",
        "textoerror"
    })
    public static class VALIDACION {

        @XmlElement(name = "CODIGO_ERROR", required = true)
        protected String codigoerror;
        @XmlElement(name = "TEXTO_ERROR", required = true)
        protected String textoerror;

        /**
         * Gets the value of the codigoerror property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCODIGOERROR() {
            return codigoerror;
        }

        /**
         * Sets the value of the codigoerror property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCODIGOERROR(String value) {
            this.codigoerror = value;
        }

        /**
         * Gets the value of the textoerror property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTEXTOERROR() {
            return textoerror;
        }

        /**
         * Sets the value of the textoerror property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTEXTOERROR(String value) {
            this.textoerror = value;
        }

    }

}
